config/routes.rb
SWEN303::Application.routes.draw do
  
  

  resources :comments

devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "static_pages/about"

  get "static_pages/info"

  get "static_pages/contact"

  get "static_pages/help"

  get "static_pages/winners"

  resources :posts

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :user_id

  belongs_to :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :description, :title, :user_id

 validates :title, :presence => true, :length => { :minimum => 4 }
  validates :description, :presence => true, :length => { :minimum => 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid
  # attr_accessible :title, :body
  devise :omniauthable



  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  unless user
    user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  user
end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



def application
	@posts = Post.all
end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	 def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
       @posts = Post.order("id DESC").page(params[:page]).per_page(5)
    if current_user
    @user = current_user.email
end 
 
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    if current_user
      @user = current_user
      @post.user_id = @user.id
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def info
  end

  def contact
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= comment.user_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Reinventing the toilet" %></title>
      <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->

      <%= stylesheet_link_tag "application", :media => "all" %>

      <!-- For third-generation iPad with high-resolution Retina display: -->
      <!-- Size should be 144 x 144 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

      <!-- For iPhone with high-resolution Retina display: -->
      <!-- Size should be 114 x 114 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

      <!-- For first- and second-generation iPad: -->
      <!-- Size should be 72 x 72 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

      <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
      <!-- Size should be 57 x 57 pixels -->
      <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

      <!-- For all other devices -->
      <!-- Size should be 32 x 32 pixels -->
      <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
    </head>
    <body>


<style type="text/css">
.scrollspy-example {
height: 200px;
overflow: auto;
position: relative;
}
</style>

<style type="text/css">
.nav-bar-james{
height: 500px;
overflow: auto;
position: relative;
}
.modal { width: 800px;   }


</style>
<script src="/twitter-bootstrap/twitter-bootstrap-v2/docs/assets/js/jquery.js"></script>
<script src="/twitter-bootstrap/twitter-bootstrap-v2/docs/assets/js/bootstrap-dropdown.js"></script>
<script src="/twitter-bootstrap/twitter-bootstrap-v2/docs/assets/js/bootstrap-scrollspy.js"></script>


<script src="assets/js/bootstrap-scrollspy.js"></script>
<script src="assets/js/jquery.js"></script>
<script src="assets/js/jquery.gridster.js"></script>
<script src="assets/js/jquery.collision.js"></script>
<script src="assets/js/jquery.coords.js"></script>
<script src="assets/js/jquery.draggable.js"></script>
<%= javascript_include_tag 'jquery', 'rails.validations'-%>
<script src="assets/js/hovercard.js"></script>





      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <a class="brand" href="/">Reinventing the Toilet</a>
            </a>

            <div class="container nav-collapse">
              <ul class="nav">
                <li><%= link_to "Winners", "/static_pages/winners"  %></li>
               <li><%= link_to "Our Mission", "/static_pages/info"  %></li>
               <li><%= link_to "Contact Us", "/static_pages/contact"  %></li>
               <li> <a href="#test_modal" data-toggle="modal"> FAQ </a></li>

            

             <% if current_user%>
             <ul class="nav pull-right"> 

              <li> <%=link_to current_user.email.to_s, "" %> </li>
              <li> <%= link_to "Sign Out", destroy_user_session_path , :method => :delete %></li>
            </ul>
            <% end %>
            <% if not current_user %>
            <%= form_for("user", :url => user_session_path) do |f| %>
            <ul class="nav pull-right"> 
            <li><%= f.text_field :email  , :class => 'input-large', :placeholder => "Email"%> </li>
            <li><%= f.password_field :password  , :class => 'input-large ' , :placeholder => "Password"%>  </li>
            <a href = <%= user_omniauth_authorize_path(:facebook) %> >
              <img src = "/assets/Facebook.png" width = 20 height =20> </a>
            <li><%= f.submit 'Log in' , :class => 'btn btn-small btn-primary'%> </li>
           
              
          </ul>
          <%end%>
          <%end%>

 </div>

        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="content">
    <div class="row">
     <br /><br /><br /><br /><br />

     <% if  @posts != nil %>

    <div class="span3 "> <div = "nav-bar-james">
            <div data-spy="scroll" data-target="#navbarExample" data-offset="1" class="scrollspy-example">
        <ul class="nav nav-list bs-docs-sidenav affix">



        <li class="active"><a href="#top"><i class="icon-chevron-right"></i> Top</a></li>
          <% @posts.each do |post| %>

          <li><a href=#<%=post.title%>><i class="icon-chevron-right"></i> <%=post.title%></a></li>


          <% end %>

         
          
        </ul>
</div>
</div>
</div>
<% end %>
    <div class="span9">

    
      <!-- <div class = "alert alert-success">
        <button type = "button" class ="close" data-dismiss="alert">x</button>
        <strong>
         Welcome to Water Sanitation, as this is your first visit so have a look around
       </strong>

     </div> -->

     <% if notice != nil or alert != nil %>
     <div class = "alert">
       <button type = "button" class ="close" data-dismiss="alert">x</button>
       <%= notice %>
       <%= alert %>

     </div>
     <% end %>



     <%= yield %>

   </div><!--/span-->
 </div><!--/row-->
</div><!--/content-->


</div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>

  <div class="modal fade large" id="test_modal">

    <a class="close" data-dismiss="modal">&times;</a>


    <div class="modal-body ">
      <div id="navbarExample" class="navbar navbar-static">
        <div class="navbar-inner">
          <div class="container" style="width: auto;">
            <a class="brand" href="#privacy">FAQ</a>

            <ul class="nav">
              <li class=""><a href="#privacy">Privacy</a></li>
              <li class=""><a href="#cookies">Cookies</a></li>
              <li class=""><a href="#concerns">Concerns</a></li>
              <li class=""><a href="#government">Government</a></li>
              <li class=""><a href="#remove">Policy</a></li>

            </ul>
          </div>
        </div>
      </div>

      <div data-spy="scroll" data-target="#navbarExample" data-offset="1" class="scrollspy-example">
        <h4 id="privacy">How do you protect my privacy?</h4> <br />
        <p>At reinventing the toilet, we are keenly aware of the trust our users place in us, and our responsibility to protect their privacy. We believe transparency and choice are the foundations of privacy. To help you make informed decisions about your own privacy, we work to let you know what information we collect when you use our products and services and how we use that information to improve your service.</p>
        <br /><h4 id="cookies">Does you use cookies?</h4><br />
        <p>Yes, like most websites we use cookies to improve your experience and to provide services and advertising. Cookies help us keep a record of your preferences, like whether you want your results in English or French, or if you use our admin panel.</p>
        <br /><h4 id="concerns">How can I contact you if I have a privacy question or complaint?</h4><br />
        <p>If you feel there has been a breach of you or someone elses privacy please enclose all appropriate information including the time and date of the acitivty and then you can contact us any time through our privacy contact form. If you prefer, you can also write to: Privacy Matters c/o James Watling 1600 Amphitheatre Parkway Mountain View, California, 94043 USA</p>
        <br /><h4 id="government">How often are you asked by governments to provide data on users?</h4><br />
        <p>Like other technology and communications companies, we receive requests from government agencies around the world to provide information about users of our services and products. To help increase transparency about these requests we have created the Government Requests Tool, which shows the number of requests that we have received that relate primarily to criminal investigations. For more information about the tool and the nature of these requests, please check the Government Requests Tool FAQ.</p>
        <br/ ><h4 id="remove">How can I remove information about myself from this website?</h4><br />
        <p>
          Like all websites, we are a reflection of the content and information publicly available on the web. we do not have the ability to remove content directly from the web, so removing search results from us or another search engine leaves the underlying content unaffected. If you want to remove something from the web, you should contact the webmaster of the site and ask him or her to make a change. Once the content has been removed and our search engine crawl has visited the page again, the information will no longer appear in our search results. If you have an urgent removal request, you can also visit our help page for more information.</p>

        </div>


      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>

      </div>
    </div>
    </html>

    <script>
    $('#navbar_side').affix() 
    </script>

    <script>
window.setTimeout(function() { $(".welcome").alert('close'); }, 2000);
    </script>

    <script>

    $('#navbarExample').scrollspy()

    </script>

app/views/posts/_form.html.erb
<% @post.errors.each do |error, message|%>


<div class="alert alert-block alert-error fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <h4 class="alert-heading">You did not enter the <%= error %> correctly!</h4>

            the <%= error %> <%= message %>
        
          </div>

<% end %>


       <%= form_for @post, :validate => true, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
   
    <div class="controls">
      <%= f.text_field :title, :class => 'input-xxlarge' %>
    </div>

  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area span7' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <h1><section id = <%= post.title %> ><%= link_to post.title, post_path(post) %></h1>
  <div class="details">
  	<div class = "well welllarge">
    <%= post.description %>
     <% User.where(:id => post.user_id).each do |row| %>
 
  <br />  <br />
          <p class = "pull-right">
        posted by: <%= row.email %>
    </p>
      <br />
   <hr>
        
       
          <u><%=l post.created_at, :format => :long %></u> 
         </p>
         
               <% end %>

<% if current_user %>
               <div class = "pull-right">
                  <%= link_to "Edit Post",
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to "Delete Post",
                      post_path(post),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-mini' %>
        </div>
        <% end %>
      </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<h1>Latest News</h1>

  <% if current_user %>
  <p align = "right">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-success' %>
  </p>
  <% end %>

<div id="posts">
  <%= render @posts.reverse! %>
 
</div>

<%= will_paginate @posts %>

app/views/posts/index.js.erb
$('#posts').append('<%= j render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 0.2 %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<div class="post">
  <h1><section id = <%= @post.title %> ><%= link_to @post.title, post_path(@post) %></h1>
  <div class="details">
    <div class = "well welllarge">
    <%= @post.description %>
     <% User.where(:id => @post.user_id).each do |row| %>
 
  <br />  <br />
          <p class = "pull-right">
        posted by: <%= row.email %>
    </p>
      <br />
   <hr>
        
       
          <u><%=l @post.created_at, :format => :long %></u> 
         </p>
         
               <% end %>


               <div class = "pull-right">
                  <%= link_to "Edit Post",
                      edit_post_path(@post), :class => 'btn btn-mini' %>
          <%= link_to "Delete Post",
                      post_path(@post),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-mini' %>
        </div>
      </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
 <div class="page-header">
 	<h2>Send us a message</h2>
 </div>
 <p>We want to hear from you! Just enter your name, email address, and message into the form below and send away.</p>

 <p>All fields are required</p>

 <form method="post" action="/contact">
 	<fieldset>
 		<div class="clearfix">
 			<br/>
 			<div class="input">
 				<div class = "span7">
 				<input type="text"  placeholder="Name">
       			
 				<input type="text" placeholder="Email">
 			</div>

</div>
 		</div>
 		<br/>
 		<div class="clearfix">
 			<label for="message"></label>
 			<div class="input">
 				<textarea tabindex="3" class="xxlarge span6" id="message" name="body" label="Message" columns = "12" rows="7" placeholder="Message"></textarea>
 			</div>
 		</div>
 		<div class="actions span2 offset4">
 			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <button class="btn btn-large btn-primary" type="button">Submit</button>
 		</div>
 	</fieldset>
 </form>
</div>

app/views/static_pages/help.html.erb
      <div data-spy="scroll" data-target="#navbarExample" data-offset="1" class="scrollspy-example">
        <h4 id="privacy">How do you protect my privacy?</h4> <br/>
        <p>At reinventing the toilet, we are keenly aware of the trust our users place in us, and our responsibility to protect their privacy. We believe transparency and choice are the foundations of privacy. To help you make informed decisions about your own privacy, we work to let you know what information we collect when you use our products and services and how we use that information to improve your service.</p>
        <br/><h4 id="cookies">Does you use cookies?</h4><br/>
        <p>Yes, like most websites we use cookies to improve your experience and to provide services and advertising. Cookies help us keep a record of your preferences, like whether you want your results in English or French, or if you use our admin panel.</p>
        <br/><h4 id="concerns">How can I contact you if I have a privacy question or complaint?</h4><br/>
        <p>If you feel there has been a breach of you or someone elses privacy please enclose all appropriate information including the time and date of the acitivty and then you can contact us any time through our privacy contact form. If you prefer, you can also write to: Privacy Matters c/o James Watling 1600 Amphitheatre Parkway Mountain View, California, 94043 USA</p>
        <br/><h4 id="government">How often are you asked by governments to provide data on users?</h4><br/>
        <p>Like other technology and communications companies, we receive requests from government agencies around the world to provide information about users of our services and products. To help increase transparency about these requests we have created the Government Requests Tool, which shows the number of requests that we have received that relate primarily to criminal investigations. For more information about the tool and the nature of these requests, please check the Government Requests Tool FAQ.</p>
        <br/><h4 id="remove">How can I remove information about myself from this website?</h4><br/>
        <p>
          Like all websites, we are a reflection of the content and information publicly available on the web. we do not have the ability to remove content directly from the web, so removing search results from us or another search engine leaves the underlying content unaffected. If you want to remove something from the web, you should contact the webmaster of the site and ask him or her to make a change. Once the content has been removed and our search engine crawl has visited the page again, the information will no longer appear in our search results. If you have an urgent removal request, you can also visit our help page for more information.</p>

        </div>


      </div>
      <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>

      </div>


         <script>

    $('#navbarExample').scrollspy()

    </script>

app/views/static_pages/winners.html.erb
<style type="text/css">

.gallerycontainer{
position: relative;
/*Add a height attribute and set to largest image's height to prevent overlaying*/
}

.thumbnail img{
border: 1px solid white;
margin: 0 5px 5px 0;
}

.thumbnail:hover{
background-color: transparent;
}

.thumbnail:hover img{
border: 0px solid black;
}

.thumbnail span{ /*CSS for enlarged image*/
position: absolute;
background-color: lightyellow;
padding: 0px;
left: -1000px;
border: 0px dashed gray;
visibility: hidden;
color: black;
text-decoration: none;
}

.thumbnail span img{ /*CSS for enlarged image*/
border-width: 0;
padding: 5px;
}

.thumbnail:hover span{ /*CSS for enlarged image*/
visibility: visible;
top: 0;
left: 230px; /*position where enlarged image should offset horizontally */
z-index: 50;
}

</style>




<h1 class ="pull-right"> Competition Winners </h1>
<br />
<br />
<br />
<br />




<div class="gallerycontainer">


<a class="thumbnail" href="#thumb"><img src="/assets/winner.jpg" width="100px" height="66px" border="0" /><span><img src="/assets/winner.jpg" height ="500px" width = "500px" /><br />Prof Michael Hoffman shows off his winning design </span></a>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Winner</h4>
<br />
<a class="thumbnail" href="#thumb"><img src="/assets/toilet.jpg" width="100px" height="66px" border="0" /><span><img src="/assets/toilet.jpg" height ="500px" width = "500px"/><br />Conventional Toilet</span></a>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Second</h4>
<br />
<a class="thumbnail" href="#thumb"><img src="/assets/toilet2.jpg" width="100px" height="66px" border="0" /><span><img src="/assets/toilet2.jpg" height ="500px" width = "500px" /><br />Waterless Toilet</span></a>

<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Third</h4>
<br />
<a class="thumbnail" href="#thumb"><img src="/assets/toilet3.jpg" width="100px" height="66px" border="0" /><span><img src="/assets/toilet3.jpg" height ="500px" width = "500px"/><br /> Inefficient Toilet</span></a>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fourth</h4>
<br />
</div>